# -*- coding: utf-8 -*-

UF_CHOICES = (
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', u'Amapá'),
    ('AM', 'Amazonas'),
    ('BA', 'Bahia'),
    ('CE', u'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', u'Espírito Santo'),
    ('GO', u'Goiás'),
    ('MA', u'Maranhão'),
    ('MT', 'Mato Grosso'),
    ('MS', 'Mato Grosso do Sul'),
    ('MG', 'Minas Gerais'),
    ('PA', u'Pará'),
    ('PB', u'Paraíba'),
    ('PR', u'Paraná'),
    ('PE', 'Pernambuco'),
    ('PI', u'Piauí'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RS', 'Rio Grande do Sul'),
    ('RO', u'Rondônia'),
    ('RR', 'Roraima'),
    ('SC', 'Santa Catarina'),
    ('SP', u'São Paulo'),
    ('SE', 'Sergipe'),
    ('TO', 'Tocantins'),
)

UF_VERBOSE_CHOICES = (
    ('AC', 'Estado do Acre'),
    ('AL', 'Estado de Alagoas'),
    ('AP', u'Estado do Amapá'),
    ('AM', 'Estado do Amazonas'),
    ('BA', 'Estado da Bahia'),
    ('CE', u'Estado do Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', u'Estado do Espírito Santo'),
    ('GO', u'Estado de Goiás'),
    ('MA', u'Estado do Maranhão'),
    ('MT', 'Estado do Mato Grosso'),
    ('MS', 'Estado do Mato Grosso do Sul'),
    ('MG', 'Estado de Minas Gerais'),
    ('PA', u'Estado do Pará'),
    ('PB', u'Estado da Paraíba'),
    ('PR', u'Estado do Paraná'),
    ('PE', 'Estado de Pernambuco'),
    ('PI', u'Estado do Piauí'),
    ('RJ', 'Estado do Rio de Janeiro'),
    ('RN', 'Estado do Rio Grande do Norte'),
    ('RS', 'Estado do Rio Grande do Sul'),
    ('RO', u'Estado de Rondônia'),
    ('RR', 'Estado de Roraima'),
    ('SC', 'Estado de Santa Catarina'),
    ('SP', u'Estado de São Paulo'),
    ('SE', 'Estado de Sergipe'),
    ('TO', 'Estado de Tocantins'),
)
